MODEL:
  MASK_ON: true
  PIXEL_STD: [57.375, 57.120, 58.395]
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
    NUM_CLASSES: 5
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 14
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 7
  RESNETS:
    DEPTH: 101
    SIZES: [[32], [64], [128], [256], [512]]
    ASPECT_RATION: [[0.5, 1.0, 2.0]]
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NUM_GROUPS: 32
    WIDTH_PRE_GROUP: 8,
    STRIDE_IN_1X1: false
  DEVICE: "cpu"
